static const char* const agk_identifiers[] = { 
"worldtoscreenx", "worldtoscreeny", "screentoworldx", "screentoworldy", "setresolutionmode", "setsyncrate", "setorientationallowed", "settransitionmode", "setdisplayaspect", "setrendertoimage", 
"setrendertoscreen", "getcl", "setscissor", "setintendeddevicesize", "usenewdefaultfonts", "getdevicewidth", "getdeviceheight", "setvirtualresolution", "updatedevicesize", "getvirtualwidth", 
"getvirtualheight", "getscreenboundsleft", "getscreenboundsright", "getscreenboundstop", "getscreenboundsbottom", "getdisplayaspect", "getorientation", "getpaused", "getresumed", "setdefaultmagfilter", 
"setdefaultminfilter", "setdefaultwrapu", "setdefaultwrapv", "setviewoffset", "setviewzoom", "setviewzoommode", "getviewoffsetx", "getviewoffsety", "getviewzoom", "sync", "break", "stepphysics", "update", 
"update2d", "update3d", "render2dback", "render", "render2dfront", "render3d", "swap", "clearscreen", "cleardepthbuffer", "setgeneratemipmaps", "timer", "resettimer", "getruntime", "getseconds", "getframetime", 
"getmilliseconds", "getdeviceid", "getnumprocessors", "sha1", "sha256", "sha512", "httpencode", "httpdecode", "setrandomseed", "random", "random", "randomsign", "setrandomseed2", "random2", "random2", "atanfull", "atanfullrad", 
"setsorttextures", "setsortdepth", "setsorttransparentdepth", "setsortcreated", "screenfps", "getpolygonsdrawn", "getverticesprocessed", "enablecleardepth", "enableclearcolor", "setbordercolor", 
"setclearcolor", "loadimage", "loadimage", "loadimage", "loadimage", "loadsubimage", "loadsubimage", "loadimageresized", "loadimageresized", "createimagecolor", "createimagecolor", "createrenderimage", 
"createrenderimage", "getimageexists", "deleteimage", "deleteallimages", "getimagewidth", "getimageheight", "setimageminfilter", "setimagemagfilter", "setimagewrapu", "setimagewrapv", "setimagemask", 
"setimagetransparentcolor", "saveimage", "getimage", "getimage", "getimagefilename", "copyimage", "copyimage", "resizeimage", "showchooseimagescreen", "ischoosingimage", "getchosenimage", "showimagecapturescreen", 
"iscapturingimage", "getcapturedimage", "decodeqrcode", "encodeqrcode", "printimage", "setimagesavepixels", "getspriteptr", "getspriteimageid", "createsprite", "createsprite", "loadsprite", "loadsprite", 
"clonesprite", "clonesprite", "createdummysprite", "createdummysprite", "getspriteexists", "deletesprite", "deleteallsprites", "setspriteimage", "setspriteimage", "setspriteadditionalimage", 
"setspriteuv", "resetspriteuv", "setspriteposition", "setspritepositionbyoffset", "setspritex", "setspritey", "setspriteangle", "setspriteanglerad", "setspritedepth", "setspriteflip", "setspritesnap", 
"setspritevisible", "setspriteactive", "getspritex", "getspritey", "getspritexbyoffset", "getspriteybyoffset", "getspriteoffsetx", "getspriteoffsety", "getspritewidth", "getspriteangle", "getspriteanglerad", 
"getspriteheight", "getspritescalex", "getspritescaley", "getspritehittest", "getspritehit", "getspritehitgroup", "getspritehitcategory", "getspritedepth", "getspritecolorred", "getspritecolorgreen", 
"getspritecolorblue", "getspritecoloralpha", "getspriteplaying", "getspritevisible", "getspriteactive", "getspritegroup", "getspritexfrompixel", "getspriteyfrompixel", "getspritepixelfromx", 
"getspritepixelfromy", "getworldxfromsprite", "getworldyfromsprite", "getspritexfromworld", "getspriteyfromworld", "setspritesize", "setspriteanimation", "addspriteanimationframe", "clearspriteanimationframes", 
"setspritespeed", "playsprite", "playsprite", "playsprite", "playsprite", "stopsprite", "resumesprite", "setspriteframe", "getspritecurrentframe", "getspriteframecount", "setspritetransparency", 
"setspriteoffset", "setspritecolor", "setspritecolorred", "setspritecolorgreen", "setspritecolorblue", "setspritecoloralpha", "setspriteuvborder", "setspriteuvoffset", "setspriteuvscale", 
"fixspritetoscreen", "setspritescale", "setspritescalebyoffset", "setspritescissor", "setspriteshader", "drawsprite", "setphysicsscale", "setphysicsgravity", "setphysicsdebugon", "setphysicsdebugoff", 
"setphysicsthreading", "setphysicsccd", "setphysicssleeping", "getphysicssolvetime", "getphysicsislandcount", "setphysicsmaxpolygonpoints", "setphysicswalltop", "setphysicswallleft", 
"setphysicswallright", "setphysicswallbottom", "createphysicsforce", "deletephysicsforce", "setphysicsforceposition", "setphysicsforcepower", "setphysicsforcerange", "setspriteshape", 
"setspriteshapebox", "setspriteshapecircle", "setspriteshapepolygon", "addspriteshapebox", "addspriteshapecircle", "addspriteshapepolygon", "clearspriteshapes", "setspritephysicscom", 
"calculatespritephysicscom", "setspritephysicson", "setspritephysicsoff", "setspritephysicsdelete", "setspritephysicsfriction", "setspritephysicsrestitution", "setspritephysicscanrotate", 
"setspritephysicsvelocity", "setspritephysicsangularvelocity", "setspritephysicsdamping", "setspritephysicsangulardamping", "setspritephysicsisbullet", "setspritephysicsmass", 
"setspritephysicsissensor", "setspritegroup", "setspritecategorybits", "setspritecategorybit", "setspritecollidebits", "setspritecollidebit", "setspritephysicsforce", "setspritephysicstorque", 
"setspritephysicsimpulse", "setspritephysicsangularimpulse", "getspritephysicsvelocityx", "getspritephysicsvelocityy", "getspritephysicsangularvelocity", "getspritephysicsmass", 
"deletejoint", "getjointexists", "createdistancejoint", "createrevolutejoint", "createprismaticjoint", "createpulleyjoint", "createmousejoint", "createlinejoint", "createweldjoint", "creategearjoint", 
"createdistancejoint", "createrevolutejoint", "createprismaticjoint", "createpulleyjoint2", "finishpulleyjoint", "createmousejoint", "createlinejoint", "createweldjoint", "creategearjoint", 
"setjointlimiton", "setjointlimitoff", "setjointmotoron", "setjointmotoroff", "setjointmousetarget", "getjointreactionforcex", "getjointreactionforcey", "getjointreactiontorque", "physicsraycast", 
"physicsraycastgroup", "physicsraycastcategory", "spriteraycastsingle", "spriteraycast", "spriteraycastgroup", "spriteraycastcategory", "getraycastspriteid", "getraycastx", "getraycasty", 
"getraycastnormalx", "getraycastnormaly", "getraycastfraction", "getspriteinbox", "getspriteincircle", "getspritecollision", "getspritedistance", "getspritedistancepoint1x", "getspritedistancepoint1y", 
"getspritedistancepoint2x", "getspritedistancepoint2y", "getfirstcontact", "getnextcontact", "getcontactworldx", "getcontactworldy", "getcontactspriteid1", "getcontactspriteid2", "getspritefirstcontact", 
"getspritenextcontact", "getspritecontactworldx", "getspritecontactworldy", "getspritecontactspriteid2", "getphysicscollision", "getphysicscollisionx", "getphysicscollisiony", "getphysicscollisionworldx", 
"getphysicscollisionworldy", "createparticles", "createparticles", "getparticlesexists", "deleteparticles", "setparticlesposition", "setparticlesdepth", "setparticlesfrequency", "setparticlesstartzone", 
"setparticlesdirection", "setparticlesvelocityrange", "setparticlesangle", "setparticlesanglerad", "setparticlesrotationrange", "setparticlesrotationrangerad", "setparticlesfacedirection", 
"setparticlessize", "setparticleslife", "setparticlesmax", "resetparticlecount", "setparticlesimage", "setparticlesvisible", "setparticlesactive", "setparticlestransparency", "setparticlescolorinterpolation", 
"getparticlesx", "getparticlesy", "getparticlesdepth", "getparticlesvisible", "getparticlesactive", "getparticlesfrequency", "getparticlesdirectionx", "getparticlesdirectiony", "getparticlesangle", 
"getparticlesanglerad", "getparticlessize", "getparticleslife", "getparticlesmaxreached", "addparticlesforce", "clearparticlesforces", "addparticlescolorkeyframe", "clearparticlescolors", 
"addparticlesscalekeyframe", "clearparticlesscales", "fixparticlestoscreen", "updateparticles", "offsetparticles", "createtext", "createtext", "gettextexists", "deletetext", "deletealltext", 
"settextstring", "settextposition", "settextx", "settexty", "settextangle", "settextanglerad", "settextalignment", "settextsize", "settextspacing", "settextlinespacing", "settextdepth", "settextvisible", 
"settextcolor", "settextcolorred", "settextcolorgreen", "settextcolorblue", "settextcoloralpha", "gettextcolorred", "gettextcolorgreen", "gettextcolorblue", "gettextcoloralpha", "settextcharposition", 
"settextcharx", "settextchary", "settextcharangle", "settextcharanglerad", "settextcharcolor", "settextcharcolorred", "settextcharcolorgreen", "settextcharcolorblue", "settextcharcoloralpha", 
"settextcharbold", "gettextcharx", "gettextchary", "gettextcharangle", "gettextcharanglerad", "gettextcharcolorred", "gettextcharcolorgreen", "gettextcharcolorblue", "gettextcharcoloralpha", 
"gettextx", "gettexty", "gettextlength", "gettexttotalwidth", "gettexttotalheight", "gettexthittest", "settextfontimage", "settextextendedfontimage", "settextfont", "settextdefaultfontimage", 
"settextdefaultextendedfontimage", "settextdefaultminfilter", "settextdefaultmagfilter", "fixtexttoscreen", "settextmaxwidth", "settextscissor", "settexttransparency", "settextbold", 
"gettextvisible", "gettextdepth", "gettextsize", "gettextspacing", "gettextlinespacing", "gettextstring", "loadfont", "loadfont", "getfontexists", "getsystemfontexists", "deletefont", "print", "print", "print", 
"printc", "printc", "printc", "setprintsize", "setprintspacing", "setprintcolor", "setprintcolor", "setprintfont", "createskeleton2d", "createskeleton2d", "getskeleton2dexists", "deleteskeleton2d", "loadskeleton2dfromspinefile", 
"loadskeleton2dfromspinefile", "loadskeleton2dfromspriterfile", "loadskeleton2dfromspriterfile", "setskeleton2dposition", "setskeleton2drotation", "setskeleton2dflip", "setskeleton2ddepth", 
"fixskeleton2dtoscreen", "setskeleton2dvisible", "getskeleton2dx", "getskeleton2dy", "getskeleton2dangle", "getskeleton2dbone", "getskeleton2dboneparent", "getskeleton2dbonex", "getskeleton2dboney", 
"getskeleton2dboneangle", "getskeleton2dbonecurrx", "getskeleton2dbonecurry", "getskeleton2dbonecurrangle", "setskeleton2dboneposition", "setskeleton2dboneangle", "setskeleton2dbonescale", 
"setskeleton2dbonemode", "playskeleton2danimation", "setskeleton2danimationframe", "setskeleton2danimationspeed", "getskeleton2dcurrenttime", "stopskeleton2danimation", "getskeleton2disanimating", 
"getskeleton2distweening", "getskeleton2danimationtime", "tweenlinear", "tweensmooth1", "tweensmooth2", "tweeneasein1", "tweeneasein2", "tweeneaseout1", "tweeneaseout2", "tweenbounce", "tweenovershoot", 
"deletetween", "gettweenexists", "settweenduration", "createtweencustom", "createtweencustom", "gettweencustomexists", "settweencustomfloat1", "settweencustomfloat2", "settweencustomfloat3", 
"settweencustomfloat4", "settweencustominteger1", "settweencustominteger2", "settweencustominteger3", "settweencustominteger4", "gettweencustomfloat1", "gettweencustomfloat2", "gettweencustomfloat3", 
"gettweencustomfloat4", "gettweencustominteger1", "gettweencustominteger2", "gettweencustominteger3", "gettweencustominteger4", "playtweencustom", "stoptweencustom", "gettweencustomplaying", 
"createtweensprite", "createtweensprite", "gettweenspriteexists", "settweenspritex", "settweenspritey", "settweenspritexbyoffset", "settweenspriteybyoffset", "settweenspriteangle", "settweenspritesizex", 
"settweenspritesizey", "settweenspritered", "settweenspritegreen", "settweenspriteblue", "settweenspritealpha", "playtweensprite", "stoptweensprite", "gettweenspriteplaying", "createtweentext", 
"createtweentext", "gettweentextexists", "settweentextx", "settweentexty", "settweentextangle", "settweentextsize", "settweentextspacing", "settweentextlinespacing", "settweentextred", "settweentextgreen", 
"settweentextblue", "settweentextalpha", "playtweentext", "stoptweentext", "gettweentextplaying", "createtweenchar", "createtweenchar", "gettweencharexists", "settweencharx", "settweenchary", 
"settweencharangle", "settweencharred", "settweenchargreen", "settweencharblue", "settweencharalpha", "playtweenchar", "stoptweenchar", "gettweencharplaying", "createtweenobject", "createtweenobject", 
"gettweenobjectexists", "settweenobjectx", "settweenobjecty", "settweenobjectz", "settweenobjectanglex", "settweenobjectangley", "settweenobjectanglez", "settweenobjectscalex", "settweenobjectscaley", 
"settweenobjectscalez", "settweenobjectred", "settweenobjectgreen", "settweenobjectblue", "settweenobjectalpha", "playtweenobject", "stoptweenobject", "gettweenobjectplaying", "createtweencamera", 
"createtweencamera", "gettweencameraexists", "settweencamerax", "settweencameray", "settweencameraz", "settweencameraanglex", "settweencameraangley", "settweencameraanglez", "settweencamerafov", 
"playtweencamera", "stoptweencamera", "gettweencameraplaying", "createtweenchain", "createtweenchain", "deletetweenchain", "cleartweenchain", "addtweenchaincustom", "addtweenchainsprite", 
"addtweenchaintext", "addtweenchainchar", "addtweenchainobject", "addtweenchaincamera", "playtweenchain", "pausetweenchain", "stoptweenchain", "gettweenchainplaying", "settweenchaintime", 
"gettweenchainendtime", "updatealltweens", "updatetweencustom", "updatetweensprite", "updatetweentext", "updatetweenchar", "updatetweenobject", "updatetweencamera", "updatetweenchain", "getrawtouchcount", 
"getrawfirsttouchevent", "getrawnexttouchevent", "getrawtouchtype", "getrawtouchstartx", "getrawtouchstarty", "getrawtouchcurrentx", "getrawtouchcurrenty", "getrawtouchlastx", "getrawtouchlasty", 
"getrawtouchreleased", "setrawtouchvalue", "getrawtouchvalue", "getrawtouchtime", "loadsound", "loadsound", "loadsoundogg", "loadsoundogg", "savesound", "playsound", "playsound", "playsound", "playsound", 
"stopsound", "deletesound", "getsoundexists", "getsoundinstances", "getsoundsplaying", "setsoundsystemvolume", "getsoundmaxrate", "getsoundminrate", "getsoundinstanceplaying", "getsoundinstancevolume", 
"getsoundinstancerate", "setsoundinstancevolume", "setsoundinstancerate", "setsoundinstancebalance", "getsoundinstanceloopcount", "stopsoundinstance", "loadmusic", "loadmusic", "setmusicfilevolume", 
"playmusic", "playmusic", "playmusic", "playmusic", "pausemusic", "resumemusic", "stopmusic", "deletemusic", "getmusicplaying", "setmusicsystemvolume", "getmusicexists", "getmusicduration", "getmusicposition", 
"seekmusic", "loadmusicogg", "loadmusicogg", "getmusicexistsogg", "setmusicvolumeogg", "playmusicogg", "playmusicogg", "pausemusicogg", "resumemusicogg", "stopmusicogg", "deletemusicogg", "getmusicplayingogg", 
"getmusicloopcountogg", "getmusicdurationogg", "getmusicpositionogg", "seekmusicogg", "setmusicsystemvolumeogg", "setmusiclooptimesogg", "setmusicloopcountogg", "recordsound", "stopsoundrecording", 
"issoundrecording", "deletefile", "getfileexists", "chooserawfile", "chooserawfile", "simplifypath", "joinpaths", "isabsolutepath", "countwindowsdrives", "getwindowsdrive", "openrawfolder", "closerawfolder", 
"getrawfoldernumfiles", "getrawfoldernumfolders", "getrawfolderfilename", "getrawfolderfoldername", "opentowrite", "opentowrite", "opentowrite", "opentowrite", "opentoread", "opentoread", "fileisopen", 
"closefile", "fileeof", "getfilesize", "getfilepos", "setfilepos", "writebyte", "writeinteger", "writefloat", "writestring", "writestring2", "writeline", "readbyte", "readinteger", "readfloat", "readstring", "readstring2", 
"readline", "str", "str", "str", "bin", "hex", "stringtobase64", "hextobase64", "val", "val", "valfloat", "left", "right", "mid", "asc", "len", "bytelen", "chr", "lower", "upper", "spaces", "findstringcount", "findstringcount", "findstring", "findstring", 
"findstringreverse", "findstringreverse", "comparestring", "comparestring", "replacestring", "stripstring", "trimstring", "truncatestring", "countstringtokens", "getstringtoken", "countstringtokens2", 
"getstringtoken2", "getcurrentdir", "getfolder", "setfolder", "getfirstfolder", "getfirstfolder", "getnextfolder", "getfoldercount", "getfoldercount", "getfirstfile", "getfirstfile", "getnextfile", "getfilecount", 
"getfilecount", "createbroadcastlistener", "createbroadcastlistener", "getbroadcastmessage", "deletebroadcastlistener", "connectsocket", "connectsocket", "getsocketconnected", "getsocketexists", 
"deletesocket", "getsocketremoteip", "flushsocket", "getsocketbytesavailable", "getsocketbyte", "getsocketinteger", "getsocketfloat", "getsocketstring", "sendsocketbyte", "sendsocketinteger", 
"sendsocketfloat", "sendsocketstring", "createsocketlistener", "createsocketlistener", "getsocketlistenerconnection", "deletesocketlistener", "hostnetwork", "hostnetwork", "setnetworknomoreclients", 
"joinnetwork", "joinnetwork", "isnetworkactive", "getdeviceip", "getdeviceipv6", "closenetwork", "setnetworklatency", "getnetworkmyclientid", "getnetworknumclients", "getnetworkfirstclient", 
"getnetworknextclient", "getnetworkclientdisconnected", "deletenetworkclient", "getnetworkclientname", "getnetworkclientping", "getnetworkserverid", "setnetworklocalinteger", "setnetworklocalinteger", 
"setnetworklocalfloat", "setnetworklocalfloat", "getnetworkclientinteger", "getnetworkclientfloat", "createnetworkmessage", "addnetworkmessageinteger", "addnetworkmessagefloat", "addnetworkmessagestring", 
"getnetworkmessagefromip", "getnetworkmessagefromclient", "getnetworkmessageinteger", "getnetworkmessagefloat", "getnetworkmessagestring", "deletenetworkmessage", "sendnetworkmessage", 
"getnetworkmessage", "setnetworkclientuserdata", "getnetworkclientuserdata", "createhttpconnection", "deletehttpconnection", "sethttphost", "sethttphost", "closehttpconnection", "sethttptimeout", 
"sethttpverifycertificate", "sendhttprequest", "sendhttprequest", "sendhttprequestasync", "sendhttprequestasync", "sendhttpfile", "gethttpresponse", "gethttpresponseready", "gethttpfile", 
"gethttpfile", "gethttpfilecomplete", "gethttpfileprogress", "seterrormode", "getlasterror", "geterroroccurred", "message", "getjoystickexists", "getrawmousex", "getrawmousey", "getrawmousewheel", 
"getrawmousewheeldelta", "getrawmouseleftpressed", "getrawmouseleftstate", "getrawmouseleftreleased", "getrawmouserightpressed", "getrawmouserightstate", "getrawmouserightreleased", 
"getrawmousemiddlepressed", "getrawmousemiddlestate", "getrawmousemiddlereleased", "getaccelerometerexists", "getgyrosensorexists", "getproximitysensorexists", "getlightsensorexists", 
"getmagneticsensorexists", "getrotationvectorsensorexists", "getrawaccelx", "getrawaccely", "getrawaccelz", "getrawgyrovelocityx", "getrawgyrovelocityy", "getrawgyrovelocityz", "getrawproximitydistance", 
"getrawlightlevel", "getrawmagneticx", "getrawmagneticy", "getrawmagneticz", "getrawrotationvectorx", "getrawrotationvectory", "getrawrotationvectorz", "getrawrotationvectorw", "getrawrotationvectorx2", 
"getrawrotationvectory2", "getrawrotationvectorz2", "getrawrotationvectorw2", "completerawjoystickdetection", "getrawjoystickexists", "getrawjoystickconnected", "getrawjoystickx", 
"getrawjoysticky", "getrawjoystickz", "getrawjoystickrx", "getrawjoystickry", "getrawjoystickrz", "getrawjoystickbuttonpressed", "getrawjoystickbuttonstate", "getrawjoystickbuttonreleased", 
"setrawjoystickdeadzone", "addvirtualjoystick", "deletevirtualjoystick", "getvirtualjoystickexists", "getvirtualjoystickx", "getvirtualjoysticky", "setvirtualjoystickalpha", "setvirtualjoystickposition", 
"setvirtualjoysticksize", "setvirtualjoystickactive", "setvirtualjoystickvisible", "setvirtualjoystickimageinner", "setvirtualjoystickimageouter", "setvirtualjoystickdeadzone", 
"addvirtualbutton", "deletevirtualbutton", "getvirtualbuttonexists", "getvirtualbuttonpressed", "getvirtualbuttonreleased", "getvirtualbuttonstate", "setvirtualbuttoncolor", "setvirtualbuttonalpha", 
"setvirtualbuttonposition", "setvirtualbuttonsize", "setvirtualbuttonsize", "setvirtualbuttonactive", "setvirtualbuttonvisible", "setvirtualbuttonimageup", "setvirtualbuttonimagedown", 
"setvirtualbuttontext", "getrawkeypressed", "getrawkeystate", "getrawkeyreleased", "getrawlastkey", "getdirectionx", "getdirectiony", "getdirectionangle", "getdirectionspeed", "getpointerpressed", 
"getpointerreleased", "getpointerstate", "getpointerx", "getpointery", "getjoystickx", "getjoysticky", "setjoystickdeadzone", "setjoystickscreenposition", "getbuttonpressed", "getbuttonstate", 
"getbuttonreleased", "setbuttonscreenposition", "starttextinput", "starttextinput", "stoptextinput", "gettextinputstate", "gettextinputcompleted", "gettextinputcancelled", "gettextinput", 
"getlastchar", "setcursorblinktime", "settextinputmaxchars", "createeditbox", "createeditbox", "geteditboxexists", "deleteeditbox", "geteditboxhasfocus", "getcurrenteditbox", "seteditboxposition", 
"seteditboxsize", "seteditboxdepth", "seteditboxbordersize", "seteditboxbordercolor", "seteditboxbackgroundcolor", "seteditboxtext", "seteditboxtextcolor", "seteditboxcursorcolor", "seteditboxfontimage", 
"seteditboxextendedfontimage", "seteditboxfont", "seteditboxtextsize", "seteditboxcursorposition", "seteditboxfocus", "seteditboxactive", "seteditboxvisible", "seteditboxborderimage", 
"seteditboxbackgroundimage", "seteditboxcursorblinktime", "seteditboxcursorwidth", "seteditboxmaxchars", "seteditboxmaxlines", "seteditboxmultiline", "seteditboxscissor", "seteditboxpasswordmode", 
"seteditboxusealternateinput", "seteditboxwrapmode", "fixeditboxtoscreen", "geteditboxtext", "geteditboxx", "geteditboxy", "geteditboxwidth", "geteditboxheight", "geteditboxchanged", "geteditboxactive", 
"geteditboxvisible", "geteditboxlines", "geteditboxcursorposition", "getmanagedspritedrawncount", "getmanagedspritecount", "getmanagedspritesortedcount", "getpixelsdrawn", "getmanagedspritedrawcalls", 
"getparticledrawnpointcount", "getparticledrawnquadcount", "getupdatetime", "getphysicstime", "getdrawingsetuptime", "getdrawingtime", "getloadedimages", "getunassignedimages", "getunassignedimagefilename", 
"getimagememoryusage", "getleapyear", "getunixfromdate", "getyearfromunix", "getmonthfromunix", "getdaysfromunix", "gethoursfromunix", "getminutesfromunix", "getsecondsfromunix", "setinneractivedetails", 
"setadmobdetails", "setadmobrewardaddetails", "setchartboostdetails", "setamazonaddetails", "setamazonadtesting", "setadmobtesting", "showfullscreenadvertadmob", "showfullscreenadvertchartboost", 
"showfullscreenadvertamazon", "getfullscreenadvertloadedadmob", "getfullscreenadvertloadedchartboost", "getfullscreenadvertloadedamazon", "showrewardadadmob", "getrewardadloadedadmob", 
"getrewardadrewardedadmob", "resetrewardadmob", "showrewardadchartboost", "cacherewardadchartboost", "getrewardadloadedchartboost", "getrewardadrewardedchartboost", "resetrewardchartboost", 
"createfullscreenadvert", "createadvert", "createadvertex", "setadvertposition", "setadvertlocation", "setadvertlocationex", "setadvertvisible", "requestadvertrefresh", "deleteadvert", "createzip", 
"createzip", "addzipentry", "closezip", "extractzip", "log", "rateapp", "rateapp", "rateapp", "requestappreview", "inapppurchasesetkeys", "inapppurchasesettitle", "inapppurchaseaddproductid", "inapppurchasesetup", 
"getinapppurchaseavailable", "inapppurchaseactivate", "getinapppurchaselocalprice", "getinapppurchasedescription", "getinapppurchasestate", "inapppurchaserestore", "getinapppurchasesignature", 
"twittersetup", "twittermessage", "facebooksetup", "getfacebookloggedin", "facebookgetuserid", "facebookgetusername", "facebookgetaccesstoken", "facebooklogin", "facebooklogout", "facebookpostonmywall", 
"facebookpostonfriendswall", "facebookinvitefriend", "facebookshowlikebutton", "facebookdestroylikebutton", "facebookgetfriends", "facebookgetfriendsstate", "facebookgetfriendscount", 
"facebookgetfriendsname", "facebookgetfriendsid", "facebookdownloadfriendsphoto", "getfacebookdownloadstate", "getfacebookdownloadfile", "notificationcreate", "getnotification", "getnotificationdata", 
"notificationreset", "setlocalnotification", "cancellocalnotification", "getlocalnotificationexists", "getlocalnotificationtime", "getlocalnotificationmessage", "makecolor", "getcolorred", 
"getcolorgreen", "getcolorblue", "drawline", "drawline", "drawbox", "drawellipse", "creatememblock", "creatememblock", "getmemblockexists", "deletememblock", "copymemblock", "getmemblocksize", "getmemblockbyte", 
"getmemblockbytesigned", "getmemblockshort", "getmemblockint", "getmemblockfloat", "getmemblockstring", "setmemblockbyte", "setmemblockbytesigned", "setmemblockshort", "setmemblockint", "setmemblockfloat", 
"setmemblockstring", "creatememblockfromimage", "creatememblockfromimage", "createimagefrommemblock", "createimagefrommemblock", "creatememblockfromsound", "creatememblockfromsound", 
"createsoundfrommemblock", "createsoundfrommemblock", "creatememblockfromfile", "creatememblockfromfile", "createfilefrommemblock", "creatememblockfromobjectmesh", "creatememblockfromobjectmesh", 
"createobjectfrommeshmemblock", "createobjectfrommeshmemblock", "setobjectmeshfrommemblock", "addobjectmeshfrommemblock", "setmeshmemblockvertexposition", "setmeshmemblockvertexnormal", 
"setmeshmemblockvertexuv", "getmeshmemblockvertexx", "getmeshmemblockvertexy", "getmeshmemblockvertexz", "getmeshmemblockvertexnormalx", "getmeshmemblockvertexnormaly", "getmeshmemblockvertexnormalz", 
"getmeshmemblockvertexu", "getmeshmemblockvertexv", "setglobal3ddepth", "createobjectbox", "createobjectbox", "createobjectcapsule", "createobjectcapsule", "createobjectsphere", "createobjectsphere", 
"createobjectcone", "createobjectcone", "createobjectcylinder", "createobjectcylinder", "createobjectplane", "createobjectplane", "createobjectquad", "createobjectquad", "createobjectfromheightmap", 
"createobjectfromheightmap", "createobjectfromobjectmesh", "createobjectfromobjectmesh", "loadobject", "loadobject", "loadobject", "loadobject", "loadobjectwithchildren", "loadobjectwithchildren", 
"saveobject", "cloneobject", "cloneobject", "instanceobject", "instanceobject", "getobjectexists", "deleteobject", "deleteobjectwithchildren", "deleteallobjects", "getobjectnumchildren", "getobjectchildid", 
"getobjectnumbones", "getobjectbonebyname", "getobjectnummeshes", "getobjectmeshname", "setobjectmeshimage", "setobjectmeshlightmap", "setobjectmeshshader", "getobjectmeshvssource", "getobjectmeshpssource", 
"setobjectmeshuvoffset", "setobjectmeshuvscale", "getobjectmeshsizeminx", "getobjectmeshsizemaxx", "getobjectmeshsizeminy", "getobjectmeshsizemaxy", "getobjectmeshsizeminz", "getobjectmeshsizemaxz", 
"fixobjecttoobject", "fixobjecttobone", "getobjectnumanimations", "getobjectanimationname", "playobjectanimation", "setobjectanimationframe", "stopobjectanimation", "resetobjectanimation", 
"setobjectanimationspeed", "getobjectisanimating", "getobjectistweening", "getobjectanimationtime", "getobjectanimationduration", "setobjectboneposition", "setobjectbonerotation", 
"setobjectbonerotationquat", "setobjectbonelookat", "setobjectbonecananimate", "rotateobjectbonelocalx", "rotateobjectbonelocaly", "rotateobjectbonelocalz", "getobjectbonename", "getobjectbonex", 
"getobjectboney", "getobjectbonez", "getobjectboneanglex", "getobjectboneangley", "getobjectboneanglez", "getobjectbonequatw", "getobjectbonequatx", "getobjectbonequaty", "getobjectbonequatz", 
"getobjectboneworldx", "getobjectboneworldy", "getobjectboneworldz", "getobjectboneworldanglex", "getobjectboneworldangley", "getobjectboneworldanglez", "getobjectboneworldquatw", 
"getobjectboneworldquatx", "getobjectboneworldquaty", "getobjectboneworldquatz", "setobjectposition", "setobjectrotation", "setobjectrotationquat", "setobjectscale", "setobjectscalepermanent", 
"moveobjectlocalx", "moveobjectlocaly", "moveobjectlocalz", "rotateobjectlocalx", "rotateobjectlocaly", "rotateobjectlocalz", "rotateobjectglobalx", "rotateobjectglobaly", "rotateobjectglobalz", 
"getobjectx", "getobjecty", "getobjectz", "getobjectanglex", "getobjectangley", "getobjectanglez", "getobjectquatw", "getobjectquatx", "getobjectquaty", "getobjectquatz", "getobjectworldx", "getobjectworldy", 
"getobjectworldz", "getobjectworldanglex", "getobjectworldangley", "getobjectworldanglez", "getobjectworldquatw", "getobjectworldquatx", "getobjectworldquaty", "getobjectworldquatz", 
"getobjectsizeminx", "getobjectsizemaxx", "getobjectsizeminy", "getobjectsizemaxy", "getobjectsizeminz", "getobjectsizemaxz", "setobjectlookat", "fixobjectpivot", "getobjectheightmapheight", 
"setobjectimage", "setobjectlightmap", "setobjectshader", "setobjectcolor", "setobjectcoloremissive", "setobjectlightmode", "setobjectscreenculling", "setobjectuvoffset", "setobjectuvscale", 
"setobjectfogmode", "setobjectdepthreadmode", "setobjectdepthwrite", "setobjectdepthbias", "setobjectdepthrange", "setobjecttransparency", "setobjectalphamask", "setobjectcullmode", "setobjectvisible", 
"getobjectdepthreadmode", "getobjectdepthwrite", "getobjectdepthbias", "getobjecttransparency", "getobjectcullmode", "getobjectvisible", "getobjectinscreen", "getobjectname", "setobjectshaderconstantbyname", 
"setobjectshaderconstantarraybyname", "setobjectshaderconstantdefault", "drawobject", "getscreenxfrom3d", "getscreenyfrom3d", "get3dvectorxfromscreen", "get3dvectoryfromscreen", "get3dvectorzfromscreen", 
"setobjectcollisionmode", "objectraycast", "objectspherecast", "objectsphereslide", "getobjectraycastnumhits", "getobjectraycasthitid", "getobjectraycastx", "getobjectraycasty", "getobjectraycastz", 
"getobjectraycastslidex", "getobjectraycastslidey", "getobjectraycastslidez", "getobjectraycastnormalx", "getobjectraycastnormaly", "getobjectraycastnormalz", "getobjectraycastbouncex", 
"getobjectraycastbouncey", "getobjectraycastbouncez", "getobjectraycastdistance", "setfogmode", "setfogcolor", "setfogsuncolor", "setfogrange", "getfogmode", "setskyboxvisible", "setskyboxskycolor", 
"setskyboxhorizoncolor", "setskyboxsuncolor", "setskyboxhorizonsize", "setskyboxsunvisible", "setskyboxsunsize", "loadshader", "loadshader", "loadfullscreenshader", "loadfullscreenshader", 
"loadspriteshader", "loadspriteshader", "setshaderconstantbyname", "setshaderconstantarraybyname", "setcameraposition", "setcamerarotationquat", "setcamerarotation", "movecameralocalx", 
"movecameralocaly", "movecameralocalz", "rotatecameralocalx", "rotatecameralocaly", "rotatecameralocalz", "rotatecameraglobalx", "rotatecameraglobaly", "rotatecameraglobalz", "getcamerax", 
"getcameray", "getcameraz", "getcameraanglex", "getcameraangley", "getcameraanglez", "getcameraquatw", "getcameraquatx", "getcameraquaty", "getcameraquatz", "setcameralookat", "setcamerarange", "setcameraaspect", 
"setcamerafov", "setcameraorthowidth", "setcamerabounds", "setcameraoffcenter", "getcamerafov", "createpointlight", "getpointlightexists", "deletepointlight", "clearpointlights", "setpointlightposition", 
"setpointlightcolor", "setpointlightradius", "setpointlightmode", "setsundirection", "setsuncolor", "setsunactive", "setambientcolor", "create3dphysicsworld", "create3dphysicsworld", "set3dphysicsgravity", 
"set3dphysicsgravity", "step3dphysicsworld", "reset3dphysicsworld", "delete3dphysicsworld", "debug3dphysicsworld", "get3dphysicstotalobjects", "get3dphysicsactiveobjects", "get3dphysicstotaljoints", 
"setobjectshapebox", "setobjectshapebox", "setobjectshapebox", "setobjectshapesphere", "setobjectshapesphere", "setobjectshapecylinder", "setobjectshapecylinder", "setobjectshapecone", 
"setobjectshapecone", "setobjectshapecapsule", "setobjectshapecapsule", "setobjectshapecapsule", "setobjectshapeconvexhull", "setobjectshapestaticpolygon", "setobjectshapecompound", 
"create3dphysicsdynamicbody", "create3dphysicsstaticbody", "create3dphysicskinematicbody", "delete3dphysicsbody", "create3dphysicsstaticplane", "set3dphysicsstaticplaneposition", 
"set3dphysicsstaticplanerotation", "delete3dphysicsstaticplane", "setobject3dphysicsgroupandmask", "getobject3dphysicsgroup", "getobject3dphysicsmask", "setobject3dphysicsmass", 
"getobject3dphysicsmass", "setobject3dphysicscansleep", "setobject3dphysicsfriction", "getobject3dphysicsfriction", "setobject3dphysicsrollingfriction", "getobject3dphysicsrollingfriction", 
"setobject3dphysicsanisotropicfriction", "setobject3dphysicsmaxlinearvelocity", "setobject3dphysicslinearvelocity", "setobject3dphysicslinearvelocity", "getobject3dphysicslinearvelocityx", 
"getobject3dphysicslinearvelocityy", "getobject3dphysicslinearvelocityz", "setobject3dphysicsangularvelocity", "setobject3dphysicsangularvelocity", "getobject3dphysicsangularvelocityx", 
"getobject3dphysicsangularvelocityy", "getobject3dphysicsangularvelocityz", "setobject3dphysicsdamping", "getobject3dphysicslineardamp", "getobject3dphysicsangulardamp", "setobject3dphysicssleepingthreshold", 
"getobject3dphysicsangularsleepingthreshold", "getobject3dphysicslinearsleepingthreshold", "setobject3dphysicsdeactivationtime", "setobject3dphysicsrestitution", "getobject3dphysicsrestitution", 
"getobject3dphysicsfirstcontact", "getobject3dphysicscontactx", "getobject3dphysicscontacty", "getobject3dphysicscontactz", "getobject3dphysicscontactvector", "getobject3dphysicscontactobjectb", 
"getobject3dphysicsnextcontact", "getobjects3dphysicscontactpositionvector", "create3dphysicspickjoint", "update3dphysicspickjoint", "delete3dphysicspickjoint", "create3dphysicshingejoint", 
"create3dphysicsconetwistjoint", "create3dphysicssliderjoint", "create3dphysicsfixedjoint", "create3dphysics6dofjoint", "set3dphysicsjointsliderangularlimits", "set3dphysicsjointsliderlinearlimits", 
"set3dphysicsjointconetwistlimits", "set3dphysicsjointhingelimits", "set3dphysicsjointbreakingthreshold", "set3dphysicsjointenabled", "get3dphysicsjointenabled", "get3dphysicsjointpositionvector", 
"get3dphysicsjointrotationvector", "delete3dphysicsjoint", "set3dphysicshingejointmotorisenabled", "set3dphysicshingejointmaxmotorimpulse", "set3dphysicshingejointmotorvelocity", 
"set3dphysicstwistjointmotorisenabled", "set3dphysicstwistjointmaxmotorimpulse", "set3dphysicstwistjointmotorrotationtarget", "set3dphysicssliderjointpoweredlinearmotorisenabled", 
"set3dphysicssliderjointmaxlinearmotorforce", "set3dphysicssliderjointtargetlinearmotorvelocity", "addobjectshapebox", "addobjectshapesphere", "addobjectshapecapsule", "addobjectshapecone", 
"addobjectshapecylinder", "saveobjectshape", "loadobjectshape", "createvector3", "createvector3", "setvector3", "deletevector3", "getvector3x", "getvector3y", "getvector3z", "getvector3distance", 
"getvector3length", "getvector3dot", "getvector3cross", "getvector3multiply", "getvector3add", "create3dphysicsray", "delete3dphysicsray", "ray3dphysicsexist", "raycast3dphysics", "raycast3dphysicsobject", 
"get3dphysicsraycastobjecthit", "get3dphysicsraycastclosestobjecthit", "get3dphysicsraycastfraction", "get3dphysicsraycastcontactposition", "get3dphysicsraycastclosestcontactposition", 
"get3dphysicsraycastnormalvector", "get3dphysicsraycastnumhits", "spherecast3dphysics", "spherecast3dphysicsobject", "create3dphysicsragdoll", "add3dphysicsragdollbone", "assignto3dphysicsragdollboneobjectbone", 
"add3dphysicsragdollhingejoint", "add3dphysicsragdolltwistjoint", "finalize3dphysicsragdoll", "delete3dphysicsragdoll", "get3dphysicsragdollexist", "get3dphysicsragdollfromboneobject", 
"is3dphysicsragdollstatic", "set3dphysicsragdollstatic", "set3dphysicsragdollbonesvisible", "set3dphysicsragdolldamping", "set3dphysicsragdollsleepingthresholds", "set3dphysicsragdolldeactivationtime", 
"set3dphysicsragdolldeactivation", "create3dphysicscharactercontroller", "delete3dphysicscharactercontroller", "get3dphysicscharactercontrollerexists", "set3dphysicscharactercontrollergravity", 
"set3dphysicscharactercontrollerfallspeed", "set3dphysicscharactercontrollerjumpspeed", "set3dphysicscharactercontrollermaxslope", "set3dphysicscharactercontrollerstepheight", 
"get3dphysicscharactercontrollermaxslope", "get3dphysicscharactercontrollergravity", "move3dphysicscharactercontroller", "rotate3dphysicscharactercontroller", "jump3dphysicscharactercontroller", 
"crouch3dphysicscharactercontroller", "stand3dphysicscharactercontroller", "debug3dphysicscharactercontroller", "set3dphysicscharactercontrollerposition", "setwindowposition", 
"setwindowsize", "setwindowsize", "setwindowallowresize", "maximizewindow", "minimizeapp", "restoreapp", "setimmersivemode", "setscreenresolution", "getdevicename", "getdevicebasename", "getdevicetype", 
"getappname", "getdevicelanguage", "setsleepmode", "setexpansionfilekey", "setexpansionfileversion", "getexpansionfilestate", "downloadexpansionfile", "getexpansionfileprogress", "setwindowtitle", 
"sleep", "setvsync", "getmaxdevicewidth", "getmaxdeviceheight", "getdevicedpi", "getapppackagename", "getdeviceplatform", "sin", "cos", "tan", "sinrad", "cosrad", "tanrad", "asin", "acos", "atan", "atan2", "asinrad", "acosrad", 
"atanrad", "atan2rad", "trunc", "floor", "ceil", "round", "sqrt", "abs", "mod", "fmod", "pow", "log", "getnumdevicecameras", "setdevicecameratoimage", "getdevicecameratype", "vibratedevice", "loadvideo", "deletevideo", "setvideodimensions", 
"playvideotoimage", "playvideo", "pausevideo", "stopvideo", "getvideoplaying", "getvideoposition", "getvideoduration", "setvideovolume", "getvideowidth", "getvideoheight", "setvideoposition", "setrawwritepath", 
"getwritepath", "getreadpath", "getdocumentspath", "setcurrentdir", "makefolder", "deletefolder", "getmultitouchexists", "getmouseexists", "getkeyboardexists", "getcameraexists", "getgpssensorexists", 
"setrawmousevisible", "setrawmouseposition", "getunixtime", "getdayofweek", "getcurrentdate", "getcurrenttime", "openbrowser", "runapp", "getapprunning", "terminateapp", "viewfile", "sharetext", "shareimage", 
"shareimageandtext", "facebookactivateapptracking", "getinternetstate", "setpushnotificationkeys", "pushnotificationsetup", "getpushnotificationtoken", "getnotificationtype", "setnotificationimage", 
"setnotificationtext", "getnfcexists", "startgpstracking", "stopgpstracking", "getrawgpslatitude", "getrawgpslongitude", "getrawgpsaltitude", "getgamecenterexists", "gamecentersetup", "gamecenterlogin", 
"getgamecenterloggedin", "getgamecenterplayerid", "getgamecenterplayerdisplayname", "gamecentersubmitscore", "gamecentershowleaderboard", "gamecentersubmitachievement", "gamecenterachievementsshow", 
"gamecenterachievementsreset", "setsharedvariableappgroup", "savesharedvariable", "loadsharedvariable", "deletesharedvariable", "firebasesetup", "firebaselogevent", "issupporteddepthtexture", 
"setantialiasmode", "rendershadowmap", "setnetworkallowclients", "kicknetworkclient", "setobjectcastshadow", "setobjectreceiveshadow", "getobjectcastshadowmode", "getobjectreceiveshadowmode", 
"getshadowmappingsupported", "setshadowmappingmode", "getshadowmappingmode", "setshadowmapsize", "setshadowrange", "setshadowbias", "setshadowlightstepsize", "setshadowsmoothing", "getshadowpolygonsdrawn", 
"loadshaderfromstring", "loadshaderfromstring", "create3dparticles", "create3dparticles", "get3dparticlesexists", "delete3dparticles", "set3dparticlesposition", "set3dparticlesfrequency", 
"set3dparticlesstartzone", "set3dparticlesdirection", "set3dparticlesvelocityrange", "set3dparticlesdirectionrange", "set3dparticlessize", "set3dparticleslife", "set3dparticlesmax", 
"reset3dparticlecount", "set3dparticlesimage", "set3dparticlesvisible", "set3dparticlesactive", "set3dparticlestransparency", "set3dparticlescolorinterpolation", "get3dparticlesx", 
"get3dparticlesy", "get3dparticlesz", "get3dparticlesvisible", "get3dparticlesactive", "get3dparticlesfrequency", "get3dparticlesdirectionx", "get3dparticlesdirectiony", "get3dparticlesdirectionz", 
"get3dparticlesdirectionrange1", "get3dparticlesdirectionrange2", "get3dparticlessize", "get3dparticleslife", "get3dparticlesmaxreached", "add3dparticlesforce", "clear3dparticlesforces", 
"add3dparticlescolorkeyframe", "clear3dparticlescolors", "add3dparticlesscalekeyframe", "clear3dparticlesscales", "update3dparticles", "offset3dparticles", "setmeshmemblockvertexcolor", 
"getmeshmemblockvertexred", "getmeshmemblockvertexgreen", "getmeshmemblockvertexblue", "getmeshmemblockvertexalpha", "setobjectmeshnormalmap", "setobjectnormalmap", "setobjectnormalmapscale", 
"setobjectmeshnormalmapscale", "startscreenrecording", "stopscreenrecording", "isscreenrecording", "deleteshader", "activatesmartwatch", "getsmartwatchstate", "sendsmartwatchdata", "receivesmartwatchdata", 
"texttospeechsetup", "gettexttospeechready", "speak", "setspeechrate", "setspeechlanguage", "isspeaking", "stopspeaking", "getspritetransparency", "setspriteshape", "setspriteshapebox", "setspriteshapecircle", 
"setspriteshapepolygon", "setspriteshapechain", "addspriteshapechain", "getspritenumshapes", "getspriteshapenumvertices", "getspriteshapevertexx", "getspriteshapevertexy", "getspritephysicscomx", 
"getspritephysicscomy", "setspritephysicsfriction", "setspritephysicsrestitution", "setspritephysicsdensity", "setspritephysicsissensor", "setspritegroup", "setspritecategorybits", 
"setspritecategorybit", "setspritecollidebits", "setspritecollidebit", "createropejoint", "createropejoint", "setjointmousemaxforce", "setjointdamping", "pausetweencustom", "resumetweencustom", 
"pausetweensprite", "resumetweensprite", "pausetweentext", "resumetweentext", "pausetweenchar", "resumetweenchar", "pausetweenobject", "resumetweenobject", "pausetweencamera", "resumetweencamera", 
"getnetworkexists", "setobjectblendmodes", "getshaderexists", "gettextalignment", "setupclouddata", "getclouddataallowed", "getclouddatachanged", "getclouddatavariable", "setclouddatavariable", 
"deleteclouddatavariable", "getdevicenetworktype", "getstorageremaining", "getstoragetotal", "checkpermission", "requestpermission", "drawtext", "setshadowcascadevalues", "arsetup", "argetstatus", 
"ardestroy", "arcontrolcamera", "ardrawbackground", "arsetplanedetectionmode", "arsetlightestimationmode", "argetlightestimate", "arhittest", "argethittestx", "argethittesty", "argethittestz", 
"argethittestnormalx", "argethittestnormaly", "argethittestnormalz", "argethittesttype", "arhittestfinish", "argetplanes", "argetplanex", "argetplaney", "argetplanez", "argetplaneanglex", "argetplaneangley", 
"argetplaneanglez", "argetplanesizex", "argetplanesizez", "argetplanesfinish", "arcreateanchorfromhittest", "arcreateanchorfromplane", "arfixobjecttoanchor", "argetanchorstatus", "ardeleteanchor", 
"deleteobjecttree", "fixspritetoskeleton2d", "setrawtouchmovesensitivity", "move3dphysicscharactercontroller", "speak", "overrideconsentadmob", "loadconsentstatusadmob", "getconsentstatusadmob", 
"requestconsentadmob", "getsupportedshadervaryings", "getspeechnumvoices", "getspeechvoicelanguage", "getspeechvoicename", "overrideconsentchartboost", "addhttpheader", "removehttpheader", 
"gethttpstatuscode", "getspeechvoiceid", "setspeechlanguagebyid", "getspriteflippedh", "getspriteinscreen", "getspriteflippedv", "drawparticles", "draw3dparticles", "setclipboardtext", "getclipboardtext", 
"seteditboxinputtype", "getexpansionfileerror", "getskeleton2ddepth", "geteditboxdepth", "getcharbuffer", "getcharbufferlength", "getrawjoystickslider", "getrawjoystickpov", "copynetworkmessage", 
"geturlschemetext", "setobjectalpha", "getobjectcolorred", "getobjectcolorgreen", "getobjectcolorblue", "getobjectalpha", "clearurlschemetext", "extractzip", "createobjectfromrawheightmap", 
"createobjectfromrawheightmap", "setobjectmeshcollisionmode", "setobjectmeshvisible", "getobjecttexturename", "getobjectnumtextures", "getrawjoystickname", "playyoutubevideo", "sharefile", 
"getnetworkmessagefromport", "createudplistener", "createudplistener", "sendudpnetworkmessage", "getudpnetworkmessage", "deleteudplistener", "extractzipasync", "getzipextractprogress", 
"getzipextractcomplete", "getwindowwidth", "getwindowheight", "cancelzipextract", "gamecenterlogout", "getimagesizefromfile", "setobjectmeshcastshadow", "setobjectshaderconstantarrayfloatbyname", 
"setobjectshaderconstantarrayvec2byname", "setobjectshaderconstantarrayvec3byname", "setobjectshaderconstantarrayvec4byname", "setshadererrormode", "setshaderconstantarrayfloatbyname", 
"setshaderconstantarrayvec2byname", "setshaderconstantarrayvec3byname", "setshaderconstantarrayvec4byname", "getobject3dphysicsmaxlinearvelocity", "isinverteddepth", "getclipspacemode", 
"istopleftorigin", "getdrawing3dsetuptime", "makecolor", "getcoloralpha", "setpresentmode", "forcepresent", "getappinstalled", "setsnapchatstickersettings", "sharesnapchatimage", "setlocalnotification", 
"getrenderername", "getnetworkclientip", "getnetworkserverip", "getrawmousefourthpressed", "getrawmousefourthstate", "getrawmousefourthreleased", "getrawmousefifthpressed", "getrawmousefifthstate", 
"getrawmousefifthreleased", "setsounddevicemode", "addnetworkmessagebyte", "getnetworkmessagebyte", "getcameraworldx", "getcameraworldy", "getcameraworldz", "fixcameratoobject", "setspriteblendmodes", 
"setadmobchildrating", "getrewardadvalueadmob", "getmemblocksha1", "getmemblocksha256", "createimagefrompngmemblock", "createimagefrompngmemblock", "createsoundfromoggmemblock", "createsoundfromoggmemblock", 
"createmusicfromoggmemblock", "createmusicfromoggmemblock", "setimagesubimages", "getinapppurchaseavailable2", "inapppurchaseresetpurchase", "getinapppurchasetoken", "fixobjecttocamera", 
"getcameraworldanglex", "getcameraworldangley", "getcameraworldanglez", "getcameraworldquatw", "getcameraworldquatx", "getcameraworldquaty", "getcameraworldquatz", "geterrormode", "setspritephysicsgravityscale", 
"getspritephysicsgravityscale", "setspritephysicsinitiallyawake", "setspritephysicsallowsleep", "getspritephysicsinertia", "getspritephysicsisbullet", "getspritephysicsisawake", 
"gettweencustomtime", "gettweencustomendtime", "cleartweensprite", "cleartweencustom", "cleartweentext", "cleartweenchar", "cleartweenobject", "cleartweencamera", "gettweenspritetime", "gettweenspriteendtime", 
"gettweentexttime", "gettweentextendtime", "gettweenchartime", "gettweencharendtime", "gettweenobjecttime", "gettweenobjectendtime", "setupnoise", "getnoisex", "getnoisexy", "getnoisexyz", "getfractalx", 
"getfractalxy", "getfractalxyz", "settextshader", "settextshaderconstantbyname", "settextshaderconstantarraybyname", "settextshaderconstantdefault", "inapppurchaseredeemoffer", "externalsdksupported", 
"externalcommand", "externalcommandint", "externalcommandfloat", "externalcommandstring", "getappreceipt", "inapppurchaseactivatewithplan", "getinapppurchasesubnumplans", "getinapppurchasesubplannumperiods", 
"getinapppurchasesubplanprice", "getinapppurchasesubplanduration", "getinapppurchasesubplandurationunit", "getinapppurchasesubplanpaymenttype", "getinapppurchasesubplantags", 
"getinapppurchasesubplantoken", "getdisplaynumcutouts", "getdisplaycutouttop", "getdisplaycutoutbottom", "getdisplaycutoutleft", "getdisplaycutoutright", "getscreenboundssafetop", 
"getscreenboundssafebottom", "getscreenboundssafeleft", "getscreenboundssaferight", "ispinappavailable", "pinapp", "isdarktheme", "getinapppurchaseisrenewing", 
};